x-base-image:
  versions:
    moc: &moc 0.12.1 
    ic-wasm: &ic_wasm 0.9.1
    mops: &mops 1.2.0
  name: &base_name "local/base"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        MOC_VERSION: *moc
        MOPS_VERSION: *mops
        IC_WASM_VERSION: *ic_wasm
    image: *base_name
  wasm:
    build:
      context: .
      args:
        IMAGE: *base_name
    volumes:
      - ./out:/project/out
    environment:
      compress : no
    command: bash --login build.sh
